// 오른쪽의 = 뒤 문구만 고치세요.
window.resumeCopyRaw = window.resumeCopyRaw || {};
window.resumeCopyRaw.tools = `
eyebrow = 05 / WORKING TOOLKIT
heading = CORE TOOLS
introduction = 기획부터 구현과 협업까지, 직접 사용하는 도구.
buildHeading = BUILD
unityName = Unity
unityDescription = 프로토타입 · 시스템 구현
csharpName = C#
csharpDescription = 게임 로직 · 기능 구현
designHeading = DESIGN & DATA
figmaName = Figma
figmaDescription = UI 기획 · 화면 설계
excelName = Excel
excelDescription = 데이터 정리 · 밸런싱
collaborationHeading = COLLABORATION
jiraName = Jira
jiraDescription = 작업 관리 · 협업
confluenceName = Confluence
confluenceDescription = 문서화 · 협업
gitName = Git & GitHub
gitDescription = 버전 관리 · 협업
aiHeading = AI
chatgptName = ChatGPT
chatgptDescription = 기획 보조 · 구현 · QA
claudeName = Claude
claudeDescription = 기획 보조 · 구현 · QA
geminiName = Gemini
geminiDescription = 기획 보조 · 구현 · QA
`;
