// 오른쪽의 = 뒤 문구만 고치세요. 숫자를 바꾸면 차트와 점도 함께 바뀝니다.
window.resumeCopyRaw = window.resumeCopyRaw || {};
window.resumeCopyRaw.play = `
playEyebrow = 06 / PLAY STYLE
playHeading = PLAY STYLE
playSubtitle = What I've played
gamesCount = 103
gamesLabel = GAMES
genresCount = 18
genresLabel = GENRES
radarCaption = TOP 6 MAIN GENRES
rpgLabel = RPG
rpgCount = 15
platformLabel = 플랫폼
platformCount = 11
roguelikeLabel = 로그라이크
roguelikeCount = 11
adventureLabel = 어드벤처
adventureCount = 9
simulationLabel = 시뮬레이션
simulationCount = 8
survivalLabel = 생존
survivalCount = 8
otherLabel = 기타
otherCount = 42

builtEyebrow = GAME DEVELOPMENT
builtHeading = WHAT I'VE BUILT
builtSubtitle = What I've made
projectsCount = 7
projectsLabel = PROJECTS
soloCount = 5
soloLabel = SOLO
teamCount = 2
teamLabel = TEAM
distributionLabel = GENRES I'VE WORKED WITH
casualLabel = 캐주얼
casualCount = 4
puzzleLabel = 퍼즐
puzzleCount = 2
runnerLabel = 런
runnerCount = 2
rogueliteLabel = 로그라이트
rogueliteCount = 1
multiplayerLabel = 멀티플레이
multiplayerCount = 1
pinballLabel = 핀볼
pinballCount = 1
toolsLabel = TOOLS
unityLabel = Unity
unityCount = 5
godotLabel = Godot
godotCount = 1
webLabel = Web
webCount = 1
distributionHeading = DISTRIBUTION
releasedLabel = 정식 출시
releasedCount = 1
webBuildLabel = 웹 빌드
webBuildCount = 2
remainingLabel = 그 외 미배포 또는 진행중
`;
